#define ACS_HLINE	"─"
#define ACS_VLINE       "│"
#define ACS_ULCORNER	"┌"
#define ACS_TTEE	"┬"
#define ACS_URCORNER	"┐"
#define ACS_LTEE	"├"
#define ACS_PLUS	"┼"
#define ACS_RTEE	"┤"
#define ACS_LLCORNER	"└"
#define ACS_BTEE	"┴"
#define ACS_LRCORNER	"┘"

